### ISSUE TITLE
system-modeller-deployment with ssm-adaptor

### ISSUE THREAD

**Issue by panositi** [Spyderisk/system-modeller-deployment#5]
Create a branch for a system-modeller-deployment including the ssm-adaptor.

**Comment by scp93ch** [comment]
We need a way to simply deploy the Java service alongside the ssm-adaptor service. This can be done by modifying the existing system-modeller-deployment scripts to include an image of the ssm-adaptor.

**Comment by panositi** [comment]
Checked for local installation and seems to work with a locally build ssm-adaptor image. However, we need to have an ssm-adaptor image on dockerhub and update `docker-config.yml`:

```
image: spyderisk/system-modeller-adaptor:${SPYDERISK_ADAPTOR_VERSION}
```
and `.env_adaptor`:
```
# Version of SPYDERISK System Modeller Adaptor to use
SPYDERISK_ADAPTOR_VERSION=dev-202310xxxx
```
